version: '3.1'

services:
  run-up-webhook:
    container_name: run-up-webhook
    build: .
    command: yarn start
    environment:
      PORT: 8000
      REDIS_URL: redis://run-up-redis:6379
    ports:
      - "8000:8000"
    networks:
      - runupto-redis_cache-network

networks:
  runupto-redis_cache-network:
    external: true
