version: '3.1'

services:
  run-up-webhook:
    container_name: run-up-webhook
    build: .
    command: yarn start
    environment:
      PORT: 80
      REDIS_URL: redis://run-up-redis:6379
      VIRTUAL_HOST: webhook.zorp.co
    expose:
      - 80
    networks:
      - runupto-redis_cache-network
      - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
  runupto-redis_cache-network:
    external: true

