version: '3.7'

services:
  run-up-webhook:
    container_name: run-up-webhook
    build: .
    command: yarn start
    environment:
      PORT: 80
      REDIS_URL: redis://run-up-redis:6379
      VIRTUAL_HOST: webhook.zorp.co
    expose:
      - 80
    networks:
      - cache-network
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
    name: nginx-proxy
  cache-network:
    external: true
    name: cache-network

